/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpringRouteImport } from './routes/spring'
import { Route as ParabolaRouteImport } from './routes/parabola'
import { Route as LinearRouteImport } from './routes/linear'
import { Route as CircularRouteImport } from './routes/circular'
import { Route as IndexRouteImport } from './routes/index'

const SpringRoute = SpringRouteImport.update({
  id: '/spring',
  path: '/spring',
  getParentRoute: () => rootRouteImport,
} as any)
const ParabolaRoute = ParabolaRouteImport.update({
  id: '/parabola',
  path: '/parabola',
  getParentRoute: () => rootRouteImport,
} as any)
const LinearRoute = LinearRouteImport.update({
  id: '/linear',
  path: '/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularRoute = CircularRouteImport.update({
  id: '/circular',
  path: '/circular',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/linear': typeof LinearRoute
  '/parabola': typeof ParabolaRoute
  '/spring': typeof SpringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/linear': typeof LinearRoute
  '/parabola': typeof ParabolaRoute
  '/spring': typeof SpringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circular': typeof CircularRoute
  '/linear': typeof LinearRoute
  '/parabola': typeof ParabolaRoute
  '/spring': typeof SpringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/circular' | '/linear' | '/parabola' | '/spring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/circular' | '/linear' | '/parabola' | '/spring'
  id: '__root__' | '/' | '/circular' | '/linear' | '/parabola' | '/spring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircularRoute: typeof CircularRoute
  LinearRoute: typeof LinearRoute
  ParabolaRoute: typeof ParabolaRoute
  SpringRoute: typeof SpringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spring': {
      id: '/spring'
      path: '/spring'
      fullPath: '/spring'
      preLoaderRoute: typeof SpringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parabola': {
      id: '/parabola'
      path: '/parabola'
      fullPath: '/parabola'
      preLoaderRoute: typeof ParabolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linear': {
      id: '/linear'
      path: '/linear'
      fullPath: '/linear'
      preLoaderRoute: typeof LinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circular': {
      id: '/circular'
      path: '/circular'
      fullPath: '/circular'
      preLoaderRoute: typeof CircularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircularRoute: CircularRoute,
  LinearRoute: LinearRoute,
  ParabolaRoute: ParabolaRoute,
  SpringRoute: SpringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
