/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotionlabsSpringRouteImport } from './routes/motionlabs/spring'
import { Route as MotionlabsParabolaRouteImport } from './routes/motionlabs/parabola'
import { Route as MotionlabsLinearRouteImport } from './routes/motionlabs/linear'
import { Route as MotionlabsCircularRouteImport } from './routes/motionlabs/circular'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionlabsSpringRoute = MotionlabsSpringRouteImport.update({
  id: '/motionlabs/spring',
  path: '/motionlabs/spring',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionlabsParabolaRoute = MotionlabsParabolaRouteImport.update({
  id: '/motionlabs/parabola',
  path: '/motionlabs/parabola',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionlabsLinearRoute = MotionlabsLinearRouteImport.update({
  id: '/motionlabs/linear',
  path: '/motionlabs/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionlabsCircularRoute = MotionlabsCircularRouteImport.update({
  id: '/motionlabs/circular',
  path: '/motionlabs/circular',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motionlabs/circular': typeof MotionlabsCircularRoute
  '/motionlabs/linear': typeof MotionlabsLinearRoute
  '/motionlabs/parabola': typeof MotionlabsParabolaRoute
  '/motionlabs/spring': typeof MotionlabsSpringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motionlabs/circular': typeof MotionlabsCircularRoute
  '/motionlabs/linear': typeof MotionlabsLinearRoute
  '/motionlabs/parabola': typeof MotionlabsParabolaRoute
  '/motionlabs/spring': typeof MotionlabsSpringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/motionlabs/circular': typeof MotionlabsCircularRoute
  '/motionlabs/linear': typeof MotionlabsLinearRoute
  '/motionlabs/parabola': typeof MotionlabsParabolaRoute
  '/motionlabs/spring': typeof MotionlabsSpringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/motionlabs/circular'
    | '/motionlabs/linear'
    | '/motionlabs/parabola'
    | '/motionlabs/spring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/motionlabs/circular'
    | '/motionlabs/linear'
    | '/motionlabs/parabola'
    | '/motionlabs/spring'
  id:
    | '__root__'
    | '/'
    | '/motionlabs/circular'
    | '/motionlabs/linear'
    | '/motionlabs/parabola'
    | '/motionlabs/spring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotionlabsCircularRoute: typeof MotionlabsCircularRoute
  MotionlabsLinearRoute: typeof MotionlabsLinearRoute
  MotionlabsParabolaRoute: typeof MotionlabsParabolaRoute
  MotionlabsSpringRoute: typeof MotionlabsSpringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motionlabs/spring': {
      id: '/motionlabs/spring'
      path: '/motionlabs/spring'
      fullPath: '/motionlabs/spring'
      preLoaderRoute: typeof MotionlabsSpringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motionlabs/parabola': {
      id: '/motionlabs/parabola'
      path: '/motionlabs/parabola'
      fullPath: '/motionlabs/parabola'
      preLoaderRoute: typeof MotionlabsParabolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motionlabs/linear': {
      id: '/motionlabs/linear'
      path: '/motionlabs/linear'
      fullPath: '/motionlabs/linear'
      preLoaderRoute: typeof MotionlabsLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motionlabs/circular': {
      id: '/motionlabs/circular'
      path: '/motionlabs/circular'
      fullPath: '/motionlabs/circular'
      preLoaderRoute: typeof MotionlabsCircularRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotionlabsCircularRoute: MotionlabsCircularRoute,
  MotionlabsLinearRoute: MotionlabsLinearRoute,
  MotionlabsParabolaRoute: MotionlabsParabolaRoute,
  MotionlabsSpringRoute: MotionlabsSpringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
